### ISSUE TITLE
Recovery without console access

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/cos-toolkit-docs#80]
We should document how to trigger a recovery when you aren't able to change the grub option selected at boot time. 

The steps are:
- Mount COS_STATE
- Edit grubconfig inside the COS_STATE parition to set GRUB_DEFAULT to recovery

**Comment by mudler** [comment]
This seems already documented here: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/configure_grub/#default-boot-entry

**Comment by mudler** [comment]
Closing
